### ISSUE TITLE
Grid material

### ISSUE THREAD

**Issue by CAPCHIK** [brianzinn/react-babylonjs#109]
How I can use [Grid material](https://doc.babylonjs.com/toolsAndResources/assetLibraries/materialsLibrary/gridMat)?

Now I use a `ref` function to set material on start
```tsx
<ground
  ref={i => this.groundRefFunc(i)}
  name="base_ground"
  width={50}
  height={50}
  subdivisions={2}>
</ground>
```

```ts
groundRefFunc(instance: any) {
  if (!instance) {
      return;
  }
  const gridMaterial = new GridMaterial("ground_material", instance._scene);
  gridMaterial.mainColor = Color3.White();
  gridMaterial.lineColor = Color3.Black();
  gridMaterial.opacity = 0.8;

  instance.material = this.gridMaterial ;
}
```

Can I use something like this?
```tsx
<ground
  name="base_ground"
  width={50}
  height={50}
  subdivisions={2}>
    <gridMaterial
      name="ground_material" 
      mainColor={Color3.White()}
      lineColor={Color3.Black()}
      opacity={0.8} />
</ground>

```

**Comment by brianzinn** [comment]
That's currently the only way to accomplish that.  The grid material is an extension and not part of the core library.  That package is nearly 1MB in size (probably mostly typings), but I'm not sure I'd want to bring in directly as a required dependency.  One thing I have been considering is dynamic registering with the reconciler to be able to render custom libraries.  I would be able to do so with just a name ("gridMaterial") a reference to the import and a properties list.  Then the properties could be registered to the renderer by type.  That would support exactly what you are after and the props would flow through when they changed.  The renderer would be able to load them similar to how I load Dynamic Terrain, which is not part of @babylonjs/core or @babylonjs/gui.

I looked at the source and made a sandbox.  I think it could be done also by generating a plugin from the typings...

Made a small code sandbox for anybody else wondering how the above was done using the materials library:
https://codesandbox.io/s/beautiful-meadow-04wg7?file=/src/index.tsx

**Comment by brianzinn** [comment]
hi @CAPCHIK - Thanks for the issue!   I've pushed an experimental 💀 feature (on v3.0.4) for dynamic host registration.  It allows custom host elements to be rendered and have prop updates flow through.  The example above was updated:
https://codesandbox.io/s/beautiful-meadow-04wg7?file=/src/App.tsx

You can see in this screen capture that a select input in DOM updates the props in the `<gridMaterial lineColor={selectedColor} />`.  I think this could be dynamically generated as a plugin library for `@babylonjs/materials`.  I'll definitely change the API at some point as this is what I had envisioned before to make GUI a plugin (and reduce library size).  I'll need to generate also the JSX for TypeScript and clean up.  I've had the idea for ages, so surprised it was only about 30 minutes to write 😄 
![dynamic-host](https://user-images.githubusercontent.com/542756/104413419-29e4aa00-5523-11eb-8071-18acc42b7d3d.gif)

**Comment by brianzinn** [comment]
going to close, since at least for what you are attempting you should be able to get it working with that.  If I had more time then I would clean that up and build a plug-in that would register the materials library.  If loading were done by side-effects then it would tree-shake whatever wasn't being used (and a default to register everything).  It would be a fun project to build - if you did want to build something like that then we could work on the API together.  It would end up possibly making this more of a mono repo, since I would like to do something similar with GUI and give this library a smaller footprint and list of dependencies (only @babylon/core and remove @babylon/gui).  Thanks for the inspiration to get this started - will be revisiting at some point 😄
