### ISSUE TITLE
Problemes with react-babylonjs 3.0.4 and react-babylon-spring

### ISSUE THREAD

**Issue by j-tdk** [brianzinn/react-babylonjs#115]
Hello, when I try to integrate react-babylon-spring into my react-babylonjs (version 3.0.4) project the spring animation doesn't update on each render. It updates just on hover. What do I wrong or does the "spring" component doesn't work with react-babylonjs in the current version 3.0.4? Can you please help me with that issue?

Here is an example:
https://codesandbox.io/s/angry-dhawan-pjfsz?file=/src/App.js

**Comment by brianzinn** [comment]
Thanks for reporting.  Something is definitely broken with the new release! I’ll be able to look this weekend.

**Comment by j-tdk** [comment]
Hey @brianzinn , Thank you very much for your help and the great react-babylonjs project!

**Comment by brianzinn** [comment]
Found the issue!  I was looking in the wrong place, so took a while to find.  It is due to the ref changing, which was an intentional breaking change of 3.x.  I had forgotten to take into account that `applyAnimatedValues` when the host is created from `@react-spring/animated` was using the  `applyInitialPropsToInstance` exported function (now I remember why it was exported...) 🤦‍♂️ 

To check I attached a property to the public host instance and that worked fine.  It's a bit messy that way, so trying to think of another way...
https://github.com/hookex/react-babylon-spring/issues/1

**Comment by brianzinn** [comment]
hi @j-tdk please give 3.0.5 a try - just published.  Note also that the registered handlers don't remain registered (I believe that broke when issue 100 was fixed).  I put a fix in the story itself for registration and also updated the registration to check name, but most likely those should be exported by `react-babylon-hook` or provided by a convenience method.
https://github.com/brianzinn/react-babylonjs/blob/master/stories/babylonjs/Integrations/reactSpring.stories.js

**Comment by j-tdk** [comment]
Hi @brianzinn, thank you very much for your help! I'll check the solution in the next days.
