### ISSUE TITLE
Unhandled Rejection (Error): Cannot find module '@babylonjs/core/Maths/math'

### ISSUE THREAD

**Issue by JLTG2020** [brianzinn/react-babylonjs#137]
When I use react-babylonjs I get this error. 
<img width="833" alt="截屏2021-05-31 下午4 48 46" src="https://user-images.githubusercontent.com/70514222/120167238-1450f200-c230-11eb-96f7-d85b3bda7291.png">

But when I use babylonjs directly,Everything is OK.

**Comment by brianzinn** [comment]
What version of  `@babylonjs/core` are you using?

**Comment by JLTG2020** [comment]
4.2.0

**Comment by JLTG2020** [comment]
> What version of `@babylonjs/core` are you using?

4.2.0

**Comment by brianzinn** [comment]
I think you need to clear `node_modules` directory and install again.

**Comment by JLTG2020** [comment]
> I think you need to clear `node_modules` directory and install again.

Thank you

**Comment by JLTG2020** [comment]
https://github.com/JLTG2020/react-ts-quick-starter

**Comment by JLTG2020** [comment]
I try to clear node_modules and yarn.lock.But it is not work.This is my repo:
https://github.com/JLTG2020/react-ts-quick-starter
I cannot find any problem.Please help me, Thank you very much!

**Comment by brianzinn** [comment]
hi @JLTG2020 sorry, I did not see that you had re-opened this issue.  What I did was downgrade to `react-babylonjs@2.3.2` and was able to get your repo started.  One big difference from 3.0 was that I added to package.json `"type": "module",`.  If I remove that from the `react-babylonjs` package.json then your project does load even on @latest.  I would defer this as a bug in your starter webpack configuration, since this project is correctly type "module".  Please re-open if you have more questions.  I stopped supported cjs quite a while ago (it was just one line in rollup configuration, though), since I am not expecting people using React to need commonjs.

**Comment by brianzinn** [comment]
I will fix this - sorry that I closed it as I thought it was the other project misconfigured.   #148 has same issue.

**Comment by brianzinn** [comment]
hi @JLTG2020 - I think it is fixed in `3.0.19`. I was able to load your example repo with my latest version linked.  Can you confirm if it is working for you now?
