### ISSUE TITLE
Model is not recognized

### ISSUE THREAD

**Issue by ccasas87** [brianzinn/react-babylonjs#16]
I've been trying to load a .glb file using a Model just like this example: https://brianzinn.github.io/create-react-app-babylonjs/withModel 

But when I do something similar in my react project, the Model component I've exported from the react-babylonjs package is a string, and of course I can't add any attribute, like rootUrl to load the file.

Could you please tell which is the best way to export the Model inside a Scene (I'm using the Scene of react-babylonjs under the alias ReactBabylonJsScene) just like in the example?

The way I'm importing the components is the following:

```
import { Scene as BabylonScene, Vector3, HemisphericLight, ArcRotateCamera } from 'babylonjs';
import { Scene as ReactBabylonJsScene, Model  } from 'react-babylonjs';
```

This is my package.json:
{
  "name": "cerf-catalog-parts",
  "version": "0.0.1",
  "private": true,
  "engines": {
    "node": ">=0.10.0"
  },
  "scripts": {
    "build": "gulp bundle",
    "clean": "gulp clean",
    "test": "gulp test"
  },
  "dependencies": {
    "@microsoft/sp-core-library": "1.7.0",
    "@microsoft/sp-lodash-subset": "1.7.0",
    "@microsoft/sp-office-ui-fabric-core": "1.7.0",
    "@microsoft/sp-webpart-base": "1.7.0",
    "@pnp/common": "^1.2.9",
    "@pnp/logging": "^1.2.9",
    "@pnp/odata": "^1.2.9",
    "@pnp/sp": "^1.2.9",
    "@pnp/spfx-controls-react": "^1.11.0",
    "@types/es6-promise": "0.0.33",
    "@types/react": "16.4.2",
    "@types/react-dom": "16.0.5",
    "@types/webpack-env": "1.13.1",
    "babylonjs": "^3.3.0",
    "babylonjs-gui": "^3.3.0",
    "babylonjs-loaders": "^3.3.0",
    "babylonjs-viewer": "^3.3.0",
    "react": "16.3.2",
    "react-babylonjs": "^1.0.3",
    "react-dom": "16.3.2"
  },
  "devDependencies": {
    "@microsoft/sp-build-web": "1.7.0",
    "@microsoft/sp-tslint-rules": "1.7.0",
    "@microsoft/sp-module-interfaces": "1.7.0",
    "@microsoft/sp-webpart-workbench": "1.7.0",
    "gulp": "~3.9.1",
    "@types/chai": "3.4.34",
    "@types/mocha": "2.2.38",
    "ajv": "~5.2.2"
  }
}

Hope you can give me a hand with this!

Cheers.

**Comment by brianzinn** [comment]
If you have imported your model already as a string then you can just use `'data:' + model`. The Model in react-babylonjs is using the `SceneLoader` to load models:
https://doc.babylonjs.com/api/classes/babylon.sceneloader

Depending on your scenario, it may make more sense to load on demand, since you will otherwise be bundling the full model. If you have a GitHub repo I'm happy to look. I'm not at a computer now to try.

**Comment by brianzinn** [comment]
I think you will also need to specify the `pluginExtension` as `.glb`.  I'll add this to one of the demos in the next day, since it's a useful scenario.

**Comment by brianzinn** [comment]
i'll get that this weekend.  been super busy, sorry.

**Comment by brianzinn** [comment]
I am not able to figure it out.  What I did was update the Model and added a data property that would in turn directly use the GLTFFileLoader:
```javascript
import React, { Component } from 'react';
import './App.css';
//import raw from 'raw.macro';
import { Engine, Scene, ArcRotateCamera, HemisphericLight, Model, Box } from 'react-babylonjs'
import { Vector3 } from 'babylonjs'
//import str2ab from 'string-to-arraybuffer'

/* eslint import/no-webpack-loader-syntax: off */
import rawGlb from '!arraybuffer-loader!./WaterBottle.glb'

class App extends Component {
  render() {
    return (
      <div className="App">
        <Engine antialias={true} adaptToDeviceRatio={true} canvasId="sample-canvas">
          <Scene>
            <ArcRotateCamera name="camera1" alpha={Math.PI / 2} beta={Math.PI / 2} radius={10.0} target={Vector3.Zero()} minZ={0.001} />
            <HemisphericLight name="light1" intensity={0.7} direction={Vector3.Up()} />
            <Model data={rawGlb} pluginExtension=".glb" onModelLoaded={(model) => {
              console.log('model:', model)
            }} onModelError={(error) => console.error('error:', error)} />
          </Scene>
        </Engine>
      </div>
    );
  }
}

export default App;
```

in the code in `react-babylonjs`, I was doing this with the data property:
```
const loader = new GLTFFileLoader()

loader.importMeshAsync(
  undefined,
  this.scene,
  undefined,
  '',
  ...,
  this.props.data).then(...);
```

I have a proper ArrayBuffer from my import.  I did notice that if you import with raw.macro or raw-loader that you end up with the same string as this playground:
https://playground.babylonjs.com/#E7C6QQ

Most things in `react-babyonjs` are exported as strings, because they are "host components" for the react renderer.  If you can get that playground working without responseType = "arraybuffer" then I am happy to update the project to include calling GLTFFileLoader with the raw data.  Let me know.

**Comment by ccasas87** [comment]
@brianzinn, first of all thanks for the effort!

I really couldn't figure it out this way because of lack of knowledge of React using JavaScript... React is something really new to me and because my project is base in a SharePoint Framework template in React using TypeScript. 
In the end, I finally could implement a 3D viewer using the babylonjs-viewer library in javascript:

```
public componentDidUpdate?(prevProps: IViewerProps, prevState: ICViewerState, snapshot: any): void {
    if(prevProps.docUrl !== this.props.docUrl) {
      // get source url for the new document url
      this._getSrcUrl();
    }
    this._createViewerById("babylonjsviewercontainer");
}
public _createViewerById (container: string) : void {
    let domContainer = document.getElementById(container);
    domContainer.innerHTML = "";
    let docUrl = domContainer.dataset["docurl"];

    if(docUrl != "undefined"){
      let formerViewer = BabylonViewer.viewerManager.getViewerById(container);
      if(formerViewer != undefined){
        BabylonViewer.viewerManager.removeViewer(formerViewer);
      }
      let viewer = new BabylonViewer.DefaultViewer(domContainer, 
        {
          scene: {
            debug: false
          },
          camera: {
            behaviors: {
              autoRotate: 0
            }
          },
          model: {
            url: docUrl
          }
        }
      );
    }    
}

public render(): React.ReactElement<IViewerProps> {
  //...
  return (
    <div id="babylonjsviewercontainer" data-docurl={sourceUrl}></div>
  );
}
```
When I have more free time I will check your sample to try to pull it out that way too :)


Cheers!

**Comment by brianzinn** [comment]
First of all I am impressed you have the Viewer working in React!  I did not understand what you were saying before and I thought that you had imported the entire model as a string (while it was just the url).  I would say that if you are just loading the model that you would only need one of the other (react-babylonjs or babylonjs-viewer), but not both.

If you want to get it working with `react-babylonjs` then you just need to convert the `sourceUrl` into two parts:
```javascript
// Tools is part of BabylonJS that you can import
var sceneFilename = Tools.GetFilename(sourceUrl)
var rootUrl = Tools.GetFolderPath(sourceUrl)
```

All of the current examples and code have the URL already split:
```jsx
<Model sceneFilename={sceneFilename} rootUrl={rootUrl} />
```

I can **add** a new property for a future version, so that you *could* do something with a full URL and not need to use 'Tools':
```jsx
<Model url={sourceUrl} />
```

**Comment by brianzinn** [comment]
actually, are you in TypeScript - are these just warnings?  The reason they are strings is because they are host components for `react-reconciler`.  I am working on another issue to generate proper typings.

**Comment by chauss** [comment]
Hey @brianzinn 
I think I have the same problem as @Telephunky right now and when I read the thread above I am not sure if you guys missed each others point completely or if I am missing all of your points.

@Telephunky said
> But when I do something similar in my react project, the Model component I've exported from the react-babylonjs package is a string, and of course I can't add any attribute, like rootUrl to load the file.

I think when he is talking from exporting he means importing as thats where my problem is.

I am simply trying to load a .glb file to have its model in my 3d scene. As I learned I can use the `<Model />` for that. But when I try to import the `Model` like `import { Model } from 'react-babylonjs';` it is importing `Model` as a `string` (as quoted above).

So now in my `render` function I can not say `<Model rootUrl="some-url" ....>`because it says 
> Property 'rootUrl' does not exist on type 'IntrinsicAttributes'

Do you know why `Model` is exported as `string` or anythink else I do wrong? Maybe I am just missing something else but as I would like to use your simple and nice syntax instead of using such a work around like @Telephunky did.

Best regards
chris

**Comment by chauss** [comment]
Ok update as I looked further into it and had some help of a college.

It seems all the examples are outdated as one should now use `<model />` instead of `<Model />`.

Is this assumption right?

**Comment by brianzinn** [comment]
Only 'model' is generated in the JSX Intrinsic Elements (https://github.com/brianzinn/react-babylonjs/blob/master/src/generatedProps.ts#L385).  It will work with 'Model', since the reconciler understands both, but 'Model' will complain in your editor (you are right, it is just an exported string).  'Model' is actually just supported for backwards compatibility.  Host elements are supposed to start with a lower case letter (ie: div, span, model).  This project has some baggage with how it has changed over time and supporting backwards compatibility.

For the upcoming v3 of this project I have decided to go with a lot of breaking changes.  The model is being moved into a separate NPM to modularize the dependencies.  I haven't decided yet if 'model' should be registered to the renderer as an optional side-load or if jsx goes back to 'Model'.  At any rate, it will be a breaking change with the support for Suspense and hooks.

**Comment by chauss** [comment]
I can totally understand how your project got a little "wild" with the time, the new features and the backwards compatibility 😄 

Can't wait for v3! It's always nice to have a big cleanup 👍
