### ISSUE TITLE
React reconciler

### ISSUE THREAD

**Issue by pkieltyka** [brianzinn/react-babylonjs#2]
Hey @brianzinn — nice work on the project

I was wondering if you've considered implementing the bablyon<>react interface as a react reconciler? https://github.com/facebook/react/tree/master/packages/react-reconciler

examples: https://github.com/michalochman/react-pixi-fiber / https://github.com/toxicFork/react-three-renderer-fiber

**Comment by konsumer** [comment]
I got a basic naive custom-renderer implementation up [here](https://github.com/konsumer/react-babylonjs-ideas). [Here](https://codesandbox.io/s/github/konsumer/react-babylonjs-ideas) is a sandbox you can play around with it in.

It seems much faster. I think the main thing it needs is automatic generation of all the bindings through static analysis of babylonjs. RIght now it's hardcoded to just support the stuff I put in the demo (meshes, `FreeCamera`, and `HemisphericLight`.) Additionally, I setup context stuff, so you can get access to `engine`, `scene`, & `canvas` easily in custom-components. I'm still not quite sure about how I am passing `scene` into children, but it works for now.

**Comment by brianzinn** [comment]
I will create a branch this weekend with all of these great changes.  I thought a bit before about how you are using MeshBuilder to do similar - Decal and GroundFromHeightMap have different factory method signatures, but that is easy to fix.  Also, the timer is using WillMount, which fires multiple times just fyi.  Anyway, those are minor, but the changes you are proposing are going to be massive improvements!! :)

I will also play around with the static generator - I don't know if you noticed in the original code how the props handlers work (ie: position: https://github.com/brianzinn/react-babylonjs/blob/master/src/MeshProps.ts#L26), but they were based on the inheritance hierarchy (and props) of components, so I will be looking at how to dynamically fit that into commitUpdate of reconciler.  The static generator is by far the best way to get full API support, so that is a life saver!!  If I can get the GUI 2D + 3D going they have strange lifecycle management with their parent dependencies and order of calls, but I think with Context it will be much cleaner.

**Comment by konsumer** [comment]
I added more code-generation, and some custom-render improvements. Not sure what you mean about timer, I double-checked that it's only firing once per interval (do double-ups or anything) maybe I am misunderstanding.

I think there is still a bit of renderer tweaking on specific tags/families in `createInstance` and better props handling. I'm not really sure what all those functions in the renderer do, and didn't have time to work out the best way to add/remove tags and mutate props. The way context is setup probly needs improvement too.

**Comment by brianzinn** [comment]
You are right @konsumer about the event firing.  I am really impressed with your latest demo.  If you check the code, I think we can share an observable method from scene onBeforeRender that provides engine deltaTime from last frame from Scene HOC, for smoother animations (like withTime).

I have been struggling with getting it to work in TypeScript and webpack building an NPM module.  TypeScript for getting the HOC syntax and NPM module with exporting the JSON.  I have created a preview branch https://github.com/brianzinn/react-babylonjs/tree/fiber-hoc - I am OK to not have many components - ie: VR/3D/GUI/Shadow/etc. as I can add them afterwards and your generated components add way more BabylonJS API support anyway - your code proposal has so many improvements that it's worth it!

I am definitely considering switching to JavaScript (maybe we could generate .d.ts!), because the TS code is unwieldly.  Here is the HOC for withEngine:
```typescript
type Omit<T, K extends keyof T> = Pick<T, Exclude<keyof T, K>>;

export function withEngine<
  P extends { engineCtx: WithEngineContext },
  R = Omit<P, 'engineCtx'>
  >(
  Component: React.ComponentClass<P> | React.StatelessComponent<P>
  ): React.SFC<R> {
  return function BoundComponent(props: R) {
    return (
      <EngineConsumer>
        {ctx => <Component {...props} engineCtx={ctx} />}
      </EngineConsumer>
    );
  };
}
```

I am unable to get `export default withEngine(Scene)` to compile.  So, kind of stuck on that and JSON export, but since I have plans for rest of day just wanted to share where I ended up.  If you want to give it a try use npm link and try to import in another project :)  cheers

**Comment by brianzinn** [comment]
whew - got the TypeScript compiling; it was just a silly mistake on my end as props needed to match.  Just need to sort out the components.json not compiling as a module!  Then we can hopefully get the rest going and publish :)

**Comment by konsumer** [comment]
I'd be happy to write a `<Animate />` and `withAnimation` that use `withEngine` if this seems like a good direction.

**Comment by konsumer** [comment]
Maybe change the name, as it's a bit confusing (it's not babylon animation.) but the basic idea could be applied to anything that should re-render on an engine-tick, and send new props to the child. Maybe `withEngineRender` would make sense, or something like that.

**Comment by konsumer** [comment]
Hmm, my comments seem to have disappeared. I will re-add them.

> So, this works, but the available controls are limited currently - this is because I did not figure out how to import components.json, so I am using a components.ts.

This could be fixed by adding json-loader to your webpack config, or we could do `default export <JSON_HERE>` in generator, to create components.ts, if you prefer that direction.

> I am definitely considering switching to JavaScript 

I get that typescript is better for many reasons, but I have also found it kind of unwieldy, probly just due to my lack of familiarity. I seem to spend a more time defining things than doing things, and it's not as easy for me to read. I could definitely contribute more, sooner, with plain ES6 code, and it's getting to the point that ES6 (with flow, if you really like defining types) can do all the same stuff. To me it feels like you should stick with whatever works for you though, and I'll do what I can to help, whichever language you choose. I think the renderer work I did could be even further simplified, and should be trimmed down as much as possible, regardless of language, to make it easier for people to contribute. One of the bonuses of a custom renderer is that it's all centralized. Very little component code, other than the renderer itself.

> I think we can share an observable method from scene onBeforeRender that provides engine deltaTime from last frame from Scene HOC, for smoother animations (like withTime).

With the built-in access to scene, it's pretty easy to do this with a component. I am going to add a `<BeforeRender>` component & `withBeforeRender` HOC that will help with this, and should improve the demo. I'll put it in my ideas repo. Since you get `componentWIllMount` and `componentWillUnmount` and `withScene` gives you access to the scene, all the pieces are basically there for attaching & tearing-down listeners.  It'd be neat to make lil components for all of them from [here](https://doc.babylonjs.com/how_to/observables):

```
<BeforeAnimations>
<AfterAnimations>
<BeforePhysics>
<AfterPhysics>
<BeforeRender>
<BeforeRenderTargetsRender>
<AfterRenderTargetsRender>
<BeforeCameraRender>
<BeforeActiveMeshesEvaluation>
<AfterActiveMeshesEvaluation>
<BeforeParticlesRendering>
<AfterParticlesRendering>
<BeforeRenderTargetsRender>
<AfterRenderTargetsRender>
<BeforeDrawPhase>
<AfterDrawPhase>
<AfterCameraRender>
<AfterRender>
```

I'll prototype it as a component, but I could see these all being added to the auto-generated code, and handled mostly in the render layer (no seperate components.)

**Comment by konsumer** [comment]
I added a BeforeRender component and HOC. You can see it in the [playground](https://codesandbox.io/s/github/konsumer/react-babylonjs-ideas)

**Comment by brianzinn** [comment]
That's exactly what I was thinking - add/remove from observable in component mount/unmount!  Much smoother and was easy to wire to your 'player' :)

**Comment by konsumer** [comment]
> Much smoother and was easy to wire to your 'player' :)

Totally. I also made a `<BeforeRender>` if people like that better. Like I said, this could probly all be done at the render-engine level for code simplicity, and added to components.json/ts.

This all makes me think of a couple engine/scene level things that I'm not sure how they should fit into all this, namely shadows & physics. How should it work? Sometimes it helps me to pretend like all the stuff is in place to do it how I want, then work backwards.

### Shadows

[demo](https://www.babylonjs.com/demos/shadows/)

For this, I think we need 3 parts: a light can generate shadows, a mesh can receive shadows, and a mesh can cast shadows. `receiveShadows ` should already work for meshes, with current seat-of-pants props system, so we still need the other 2. I was thinking a light could have a `shadows` prop that is bool/int, so you can do `< DirectionalLight  shadows />` for default map-size, and also set it to a number, if you need a different size. So maybe meshes could also have a `castShadows` param that uses name(s) of cameras as string/string[]?

So I could imagine the above demo looking something like this:

```jsx
const RotatingTorus = ({ x = 0, y = 0, z = 0, ...props }) => (
  <Torus rotation={Vector3(x, y, z)} y={6} tessellation={32} updatable={false} {...props}>
    <StandardMaterial diffuseColor={new Color3(0.5, 0.5, 0.5)} specularColor={new Color3(0.5, 0.5, 0.5)} />
  </Torus>
)

const t1 = { name: 'torus1', x: 0, z: 0, diameter: 8, thickness: 2, castShadows: 'light1' }
const Torus1 = withBeforeRender(d => {
  t1.x += 0.01
  t1.z += 0.02
  return t1
})(RotatingTorus)

const t2 = { name: 'torus2', x: 0, y: 0, diameter: 4, thickness: 1, castShadows: 'light2' }
const Torus2 = withBeforeRender(d => {
  t2.x += 0.02
  t2.y += 0.01
  return t2
})(RotatingTorus)

const c = { name: 'camera', alpha: 0, beta: 0, radius: 10, direction: new Vector3.Zero() }
const AnimatedCamera = withBeforeRender(d => {
  if (c.beta < 0.1) { c.beta = 0.1 } else if (c.beta > (Math.PI / 2) * 0.99) { c.beta = (Math.PI / 2) * 0.99 }
  if (c.radius > 150) { c.radius = 150 }
  if (c.radius < 5) { c.radius = 5 }
  return c
})(ArcRotateCamera)

export default () => (
  <Engine>
    <Scene>
      <AnimatedCamera />
      <DirectionalLight name='light1' shadows direction={Vector3(0, -1, -0.2)} y={30} intensity={0.6} />
      <DirectionalLight name='light2' shadows direction={Vector3(-1, -2, -1)} x={10} y={20} z={10} intensity={0.6} />
      <Ground name='ground' width={1000} height={1000} receiveShadows>
        <Texture diffuseTexture url='grass.jpg' uScale={60} vScale={60} specularColor={new Color3(0, 0, 0)} y={-2.05} />
      </Ground>
      <Box name='skybox'>
        <StandardMaterial backFaceCulling={false} diffuseColor={new Color3(0, 0, 0)} specularColor={new Color3(0, 0, 0)} disableLighting>
          <CubeTexture reflectionTexture rootUrl='../../assets/skybox/night' coordinatesMode={Texture.SKYBOX_MODE} />
        </StandardMaterial>
      </Box>
      <Torus1 />
      <Torus2 />
    </Scene>
  </Engine>
)
```

This will need other things in place (namely texture stuff) but should be a pretty nice way to setup the same scene.

**Comment by konsumer** [comment]
I think another way to approach these things is to not overuse the `children` metaphor, if it doesn't make sense. For example, with shadows, make a manager that goes and finds all the other pieces:

```jsx
export default () => (
  <Engine>
    <Scene>
      <AnimatedCamera />
      <ShadowGenerator renderList={['torus1', 'torus2']} light='light1' />
      <ShadowGenerator renderList={['torus1', 'torus2']} light='light2' />
      <DirectionalLight name='light1' direction={Vector3(0, -1, -0.2)} y={30} intensity={0.6} />
      <DirectionalLight name='light2' direction={Vector3(-1, -2, -1)} x={10} y={20} z={10} intensity={0.6} />
      <Ground name='ground' width={1000} height={1000} receiveShadows>
        <Texture diffuseTexture url='grass.jpg' uScale={60} vScale={60} specularColor={new Color3(0, 0, 0)} y={-2.05} />
      </Ground>
      <Torus1 />
      <Torus2 />
    </Scene>
  </Engine>
)
```

Or even completely break from all the current structures, for the sake of less code, like no `<ShadowGenerator />`, just this:

```js
<DirectionalLight name='light1' direction={Vector3(0, -1, -0.2)} y={30} intensity={0.6} shadowList={['torus1', 'torus2']} />
```

like the options are basically:

* meshes push themselves into a light's shadow-manager with a `castShadows` prop
* a seperate `ShadowGenerator` tracks meshes + lights for a shadow-rendering
* lights track their shadow-meshes with a prop (like `shadowList`)

**Comment by brianzinn** [comment]
This project is now using react-reconciler!  Currently NPM version '1.0.0-beta.1' available with tag 'next'.  This version has much higher API coverage and is easier to use.  Will be updating create-react-app-babylonjs to v1.0, updating samples in readme, fixing some minor issues and releasing as v1 in another week or so.  Thanks for the great idea :)
