### ISSUE TITLE
How to use special shaders, like FresnelParameters

### ISSUE THREAD

**Issue by the-simian** [brianzinn/react-babylonjs#20]
Firstly: wow what a cool project. I love it.

I've been going over the demos and reading the source. I'm curious how you do special shaders. I'd love to see a react implementation of some of the BPR or Fresnel Demos!

like this (Frresnel):
https://www.babylonjs-playground.com/#AQZJ4C#0

also this (PBR):
https://www.babylonjs.com/demos/pbr/

if I can figure it out first I'll post the solution here and make a PR for your demo app, if you already know how to do this, can you reply? thank you!

**Comment by brianzinn** [comment]
Thanks! I haven't tried what you are after yet...

PBR is mostly a Skybox with special materials. I added a skybox here:
https://github.com/brianzinn/react-babylonjs/blob/master/src/customComponents/Skybox.ts

It relies on `react-reconciler` host components, which is why it looks like adding DOM elements. Anyway, also the materials have been generated, too. There are actually 11 kinds of materials generated, but I haven't tried the PBR ones personally.

Also, to add shader code, you can register on the engine your shaders repository:
https://github.com/brianzinn/react-babylonjs/blob/master/src/Engine.tsx#L45

The Fresnel can't be done right now declaratively :( currently you can't assign Fresnel parameters or textures as properties. ie: if you declare a FresnelParameter then how do I know which property to sign to? Need another prop to link back to parent prop name? That could be added as a custom prop. Also Cube texture is not implemented yet...

**Comment by the-simian** [comment]
I think the fact CubeTexture was not implemented, that's where I was getting hung up... I appreciate the reply. 

Do you plan on adding support for this sort of thing at any point? I know this is a heft project, and it can already certainly do a lot, so I don't want to sound like I'm pressuring you to do a lot of work. I am trying to get a sense of what the future of the project is, and if you eventually want to be feature-complete with Babylon itself or not. I am trying to determine if I could help on this particular portion or if you already have plans.

**Comment by brianzinn** [comment]
I do plan on adding support for everything currently code generated, so it can be declaratively used.  I need to add some kind of discriminator property on child controls (ie: `<FresnelParameter ../>` child component needs to know which parent property to attach to) - same thing with Textures.  There is no timeline and no work planned for next 4 weeks.

My last big push was for code generation, which is what added many of the components you are noticing have properties that do not work declaratively (you can always use the on created handler to add your own non-declarative code).  Unfortunately, the ones you are using are not implemented other than the code generation.  It is going to require additional custom props and a different lifecycle to attach to specific parent properties.  I want to concentrate first on 4.0 BabylonJS compatibility and investigate tree shaking before adding more feature-completeness.  I'd really like to expand the demo with a declarative PBR scene (currently there is only a CubeTexture demo [Skybox demo](https://brianzinn.github.io/create-react-app-babylonjs/withSkybox).

**Comment by the-simian** [comment]
I think that implementing Babylon4.0 first is sensible, then you can implement these sort of things when that's in place.

**Comment by brianzinn** [comment]
I think everything you were trying to do should be possible soon.  I just did a small PR to make it easier to declare:
https://github.com/BabylonJS/Babylon.js/pull/7818

Also, a storybook was added with some recent work on textures:
https://brianzinn.github.io/react-babylonjs/?path=/story/textures--image-texture

I'll try to make some storybook demos from the original playground links from your first comment once that PR goes to NPM :)

**Comment by brianzinn** [comment]
https://brianzinn.github.io/react-babylonjs/?path=/story/textures--fresnelparameters

**Comment by brianzinn** [comment]
https://brianzinn.github.io/react-babylonjs/?path=/story/textures--pbr

Will be out on next NPM.  They are for the 2 demos in your original issue and are nearly 100% declarative.
