### ISSUE TITLE
Babylon.js 4.0 support

### ISSUE THREAD

**Issue by thoebert** [brianzinn/react-babylonjs#22]
Hi,

I tried to use your default react-babylonjs js template with the upgraded babylon.js 4.0.3 packages, which fails with a TypeError: "Cannot read property 'x' of undefined" for each child of the scene. I am not sure if this is a bug, but I guess 4.0 of babylon.js is currently not supported?

Thank you!

**Comment by brianzinn** [comment]
Thanks for reporting.  I am planning to test everything is working with 4.0 now that it has been officially released.  I actually did a few PRs for BabylonJS 4.0, but have not had time to update *this* project.  I won't have time to test it out until end of June, though.  Do you have a public GitHub repo to see - from what I know it should be fully backwards compatible.  Note that babylonjs is a peer dependency only, so it needs to be imported still.  I am planning a bunch of work in June to be 4.0 compatible.

**Comment by thoebert** [comment]
I am using it in a public project ([elvis](https://github.com/thoebert/elvis)), but I can not add any children to my scene. It is easy to reproduce the error by cloning your starter kit (`create-react-app-babylonjs`) and changing the following dependencies "`babylonjs": "^4.0.0", "babylonjs-gui": "^4.0.0", "babylonjs-loaders": "^4.0.0"`. I am not sure how the imports should be different. Thank you!

**Comment by brianzinn** [comment]
I looked at your project - looks very cool!   I do not see any good reason why 4.0 would not upgrade cleanly.  I suspect it may be related to tree shaking, but I'm not able to check for a few weeks as I'm abroad.  If there's nothing you need in 4.0 then I'd suggest dropping down - otherwise for how you are using the project, you would get away with following an outdated article I put on their main site: https://doc.babylonjs.com/resources/babylonjs_and_reactjs (use explicit imports though).

**Comment by brianzinn** [comment]
react-babylonjs v2 fully supports babylonjs 4+.  It is a breaking change as it now only works with '@babylonjs/*` ES6 NPM modules.  react-babylonjs v2 also adds all of the Intrinsic Elements for intellisense and compile time property checking.  I have updated the TypeScript demo:
https://github.com/brianzinn/create-react-app-typescript-babylonjs
