### ISSUE TITLE
How to use svg as texture from local path

### ISSUE THREAD

**Issue by alexbom** [brianzinn/react-babylonjs#224]
Hi! I need to load svg from local path as texture of mesh:

            <cylinder ...>
                <standardMaterial name="some-material">
                    <texture
                        url={"../assets/svg/some-image.svg"}
                        assignTo="diffuseTexture"
                    />
                </standardMaterial>
            </cylinder>

But it works only with remote URLs.
With non-declarative style we can use something like this: https://playground.babylonjs.com/#NT70VN#2
But how to use local svg in react-babylon?

**Comment by brianzinn** [comment]
Is that The same as this?
https://github.com/brianzinn/react-babylonjs/blob/master/packages/storybook/stories/babylonjs/Textures/pbr.stories.js#L147

**Comment by alexbom** [comment]
Could you give an example, please?
I've tried to release this in sandbox, but unsuccessfull.
https://codesandbox.io/s/sleepy-cerf-5dghvn

**Comment by brianzinn** [comment]
seems to work just by applying to the url that same as your PG.  I only changee to "emissiveTexture" so that it was easier to see:
![image](https://user-images.githubusercontent.com/542756/170888590-1fa54841-6440-44d5-9f66-bee419eadeb0.png)
fork of your sandbox:
https://codesandbox.io/s/magical-elgamal-hg02q0?file=/src/App.tsx

**Comment by alexbom** [comment]
Thanks! It works
