### ISSUE TITLE
This repo should be marked as "not usable".

### ISSUE THREAD

**Issue by hannahroksanne** [brianzinn/react-babylonjs#319]
The docs are sooo bad. Its like...

Oh you need to see that other file? Check out the [CodeSandbox](https://codesandbox.io/p/sandbox/codesandbox-react-jsx-5d9jq5?extends=file%3A%2Fhome%2Frunner%2Fwork%2Freact-babylonjs%2Freact-babylonjs%2Fdevtool%2Floader%2Fdist%2F..%2Fsrc%2Fcodesandbox-templates%2Fjs&file=%2Fsrc%2FApp.jsx%3A7%2C8-7%2C31&fontsize=14px&hidenavigation=0&module=%2Fsrc%2FApp.jsx&template=default&theme=dark).

Oh [here's an example](https://brianzinn.github.io/react-babylonjs/examples/basic/instanced-mesh-hex/) where we do some off the wall BS that abstracts how you would actually do the thing.

There is just... no consideration that the reader doesn't know what the author knows.

This is crazy. At first, I noticed the fractured docs and determined I could just figure it out and then contribute to improving them.

But I was wrong. I've spent almost 2 weeks spinning my wheels on this and I am thinking I was better off using Three. -_-

/rant

**Comment by brianzinn** [comment]
Thanks for the feedback!  For the sandbox the file `ScaledModelWithProgress.tsx` should be included with the template or put inline.  The actual file is in the repo, so it's an easy fix.  I will add that I'm getting paid exactly 0$ to work on this repository in my spare time, so you can imagine how nice it feels to be told all of your work and work from other constributors is "not usable"! 😄 

The example with instancing is just meant to show an example.  An InstancedMesh will reduce draw calls, which is an optimization technique used in the real-world.  This is the most negative feedback actually that I have had in ~5 years and there are approximately 10K downloads/month of the library.  In that regard I will take your comments with a grain of salt.

I have spent more time actually on the docs than the code 😆 The original examples were in storybook and the community feedback via issues was that there wasn't enough explanation of especially some of the custom features or the conventions (like how Materials are attached to Meshes).  So, the docs were rewritten from the ground up last year and included links to Code Sandbox for editing.  I tried to base the documentation around a newcomer with zero knowledge.  Unfortunately, besides a broken playground and an example that to me seems perfectly OK then there's not really enough constructive feedback to make improvements to help the next stuck person.

There's a big learning curve to picking up on 3D libraries - There's not a huge difference in syntax between how this and R3R work.  Either way a good understanding of the underlying 3D library will be needed with or without a renderer.

From your profile it looks like you may be new to programming.  I would encourage you to take the time to ask for help instead of criticizing in a way that doesn't seem very constructive.  There's no reason to spend 2 weeks spinning wheels - the community is really helpful.  Babylon.js has a forum supported by Microsoft employees and lot of volunteers that genuinely want to help. Plus there is a discord, stackoverflow, etc.  I think you will have less frustration and get a lot more out of programming just by asking for more help.  Cheers.

**Comment by oatkiller** [comment]
I like this project

**Comment by konsumer** [comment]
> In that regard I will take your comments with a grain of salt.

Ugh, yes.

Listen up @hannahroksanne - @brianzinn  knows what they're talking about. This repo is extremely usable, and there are tons of examples to prove it, which is super-nice of @brianzinn to provide you for free, on their own time.

I also have some free life-advice for you: it's unwise to go around making nonconstructive negative comments like this, in any circle, IRL or online, not just on Github. You will make lots of enemies and people will generally see you as a "whiny baby with basic skill-issues that can't cope" rather than a "a humble student learning their trade", which is the hero everyone can relate to, and tries to help, in their quest. You set your self up as "the villain of the piece" and no one cries when a villain is thwarted, especially by their own petty issues. In the future, channel in yourself the humility, introspection, and grace that @brianzinn has shown you.

In this situation, you are not this guy (experienced and capable, even if they are an asshole):

![](https://d3h1lg3ksw6i6b.cloudfront.net/media/image/2021/05/21/e5239df975474556969d81bf40d010c3_Restaurant+Lingo+Talk+Like+A+Chef+5.jpg)

you are at the very beginning of your journey:

![](https://d3h1lg3ksw6i6b.cloudfront.net/media/image/2021/05/21/c2d884927aa6414ea13503263b448369_Restaurant+Lingo+Talk+Like+A+Chef+1.jpg)

You need to suck it up and quietly fry thousands of eggs, or whatever. That is how you learn things, and build a reputation. Try making anything (I saw your github, pretty paltry.)

What is the expected outcome of this issue, in the first place? Ok, you don't like react-babylonjs, but since this lib very closely follows the existing babylonjs API, and it's meant to be used in react, I'm not sure what you expect anyone to do about your sadness at not being able to make anything with it. It basically could not look any other way and follow that path, and there are plenty of docs. If threejs works better for you, use that instead, but this is a popular repo, with lots of projects using it, so we must be something right over here, even if it's incomprehensible to you.

More flies with honey and all that, but really, no one owes you code, features, support, their time, or anything else for free. Get a grip.
