### ISSUE TITLE
Merge Meshes

### ISSUE THREAD

**Issue by jm-bh** [brianzinn/react-babylonjs#324]
I'm using `react-babylonjs` to follow the [Babylon tutorial](https://doc.babylonjs.com/features/introductionToFeatures/chap2/combine/). We're supposed to merge the box and cylinder into a single mesh so we can apply transformations to the whole mesh as opposed to each component.

React is awesome because it's all about composing small components into bigger, reusable components. As a Babylon (and 3D graphics) newbie, this seems like the perfect parallel -- let's combine the meshes into a bigger, reusable mesh. **Does `react-babylonjs` offer a declarative way (such as a `<mergeMeshes>` component) to merge meshes? Could it be implemented?**

The only other thing I can think to do is to make a component which accepts position, rotation, etc. vectors, then merges the values from props with those of the children. Is that the recommended approach?

**Comment by brianzinn** [comment]
hi @jm-bh 

Static methods are an interesting thing when declarative.  The one you are looking at for example, it disposes the source meshes by default.
https://doc.babylonjs.com/typedoc/classes/BABYLON.Mesh#MergeMeshes

So, there could be a declarative way.  It could be implemented similar to full screen GUI.  In this sample I take the content of the ADT and apply it to the parent mesh (static method):
https://[brianzinn.github.io/react-babylonjs/examples/gui/2d-gui/](https://brianzinn.github.io/react-babylonjs/examples/gui/2d-gui/)

https://doc.babylonjs.com/typedoc/classes/BABYLON.GUI.AdvancedDynamicTexture#CreateForMesh
I use a prop `CreateForParentMesh` to indicate `CreateForMesh` using the parent node in the tree graph.

It wouldn't take too much work - something like:
```jsx
<mesh mergeChildMeshes>
  [
   <mesh .../>,
   <mesh .../>
  ]
</mesh>
```

Since `Mesh.MergeMeshes` returns a `Mesh` object - then you would want it to be a prop of `<mesh .../>`.  I think it's a pretty limited use case in the sense that this has never come up before.  The Mesh object typings would need to be extended to have that as an optional parameter.  Also, it would need a deferred lifecycle if Models, materials, etc. are loaded.

I agree it is nice to consider writing that declaratively.  I'm always navigating between supporting this kind of functionality and maintaining simplicity.  When I deviate from the API by supporting static methods - it does add further support of the Babylon.js API, but also a maintenance/documentation burden and can even add to confusion or complaints of complexity.  The reconciler is based off of instance methods - that's how it can maintain a mapping to each instance in Babylonj.js space to React.

I suppose I haven't given an answer, but more explained the trade-offs.  What do you think?

**Comment by jm-bh** [comment]
Okay, awesome, thank you for taking the time to write out a reply. There's a ton of information here.

Do I understand correctly that `react-babylonjs` operates primarily with instance methods, and that static methods generally should be called imperatively? I can work with that. It's a lot different than the React paradigm, but then again, there's a lot more to working with 3D than just drawing a couple `<div />`s on the screen.

Let me play with the library more, especially now that I know the design philosophy. It looks like I'm going to get a ton of practice with `useRef()` and `useEffect()` ;)

Feel free to close the ticket after your reply

**Comment by brianzinn** [comment]
yeah, you can probably get pretty far from this example:
https://[brianzinn.github.io/react-babylonjs/examples/basic/extrude-csg/](https://brianzinn.github.io/react-babylonjs/examples/basic/extrude-csg/)

If you need to access the mesh afterwards there is a custom `fromInstance` prop that allows the babylon.js mesh to receive prop updates.
https://[brianzinn.github.io/react-babylonjs/examples/basic/from-instance/](https://brianzinn.github.io/react-babylonjs/examples/basic/from-instance/)

**Comment by brianzinn** [comment]
kindly re-open if you have any more questions.  if you want to share an example it can be added to the project to help others.  i'd be happy to help get it merged.
