### ISSUE TITLE
useAssetManager example is broken

### ISSUE THREAD

**Issue by xzwang2005** [brianzinn/react-babylonjs#325]
Error:
```
RangeError
byte length of Float32Array should be a multiple of 4
eval
/src/App.jsx:41:21
```
<img width="684" alt="Screenshot 2024-12-07 at 9 05 11 AM" src="https://github.com/user-attachments/assets/d8f75208-cc83-4b3e-bb9e-ea21e9983a20">

**Comment by brianzinn** [comment]
Are you sure your assets are being served? Can you share a repro?

**Comment by xzwang2005** [comment]
ah, sorry for missing the key info.

I was trying out the example (https://brianzinn.github.io/react-babylonjs/examples/hooks/asset-manager/) in sandbox:
<img width="1746" alt="Screenshot 2024-12-08 at 9 28 01 AM" src="https://github.com/user-attachments/assets/6ac60d11-dcbb-4804-8136-8a7b45f4d3f9">

**Comment by brianzinn** [comment]
that's because the file isn't available on the codesandbox.  it's here:
https://github.com/brianzinn/react-babylonjs/tree/master/packages/static/static/assets/kitti

you can see the 00000.bin file returns HTML content in the code sandbox.  If you put that file in codesandbox then it will serve and the example will work.

**Comment by brianzinn** [comment]
Kindly re-open if not solved for you.
