### ISSUE TITLE
some issues with this package

### ISSUE THREAD

**Issue by meteorplus** [brianzinn/react-babylonjs#4]
Hello Brian,

I'm having lots of issues using this package like this is not working with SSR which you can fix by checking if window object is defined and not load the Image object and others.

also, the last example is not working AT ALL

https://github.com/brianzinn/react-babylonjs#setting-up-a-react-component-in-your-project-using-onscenemount

engine says not defined and many other things...

Thanks

**Comment by brianzinn** [comment]
For real SSR of a scene you are going to need to use the NullEngine for one.  I can add a hook for you to create your own engine no problem.  Also, about checking for window object - do you mean for the GUI image?  I don't understand why you are trying to render a canvas SSR as otherwise you could already enclose the entire thing as
{ window !== undefined &&
  <Scene..../>
}

About the engine not defined - have you imported 'babylonjs' into your project (it's only a peer dependency, so you need to supply it yourself)?

I will add a full example tomorrow with onSceneMount() and that's probably the best starting point! :)

**Comment by brianzinn** [comment]
The engine was removed as a property from onSceneMount(e) args.  I will update the docs for that.  In the meantime, here is an example:
```javascript
  onSceneMount(e) {
    const { canvas, scene } = e

    // Scene to build your environment, Canvas you need to attach your camera.       
    var camera = new ArcRotateCamera("Camera", 0, 1.05, 6, Vector3.Zero(), scene)
    camera.attachControl(canvas)

    MeshBuilder.CreateBox('box', { size: 3}, scene)
    new HemisphericLight('light', Vector3.Up(), scene);

    scene.getEngine().runRenderLoop(() => {
        if (scene) {
            scene.render();
        }
    });
}
```

**Comment by meteorplus** [comment]
Thank you for your responsiveness 

I was trying to show only the full bablyonjs viewer with the inspector!

I ended up importing dynamically the bablyonjs viewer


Same with your package I had to import it dynamically since my whole app is using ssr to pre render any page.

**Comment by brianzinn** [comment]
Would it be helpful if we added a noSSR prop to scene.  ie: <Scene noSSR={true} />?
Then when building the scene, I can not call the render methods?  I think without dynamic loading you were not even able to compile?  If there are any changes that can be made to the project to support not requiring dynamic imports they can be added.
Also, the docs have been updated and clearly indicate the breaking change:
https://github.com/brianzinn/react-babylonjs#setting-up-a-react-component-in-your-project-using-onscenemount

Thanks for reporting the issue.  I'll keep this open - if there's anything that can be added.  Cheers.

**Comment by meteorplus** [comment]
Awesome man yes a noSSR would be good too or even just checking if window is defined otherwise don't load the scene.. 

Also please use the https://codesandbox.io for code example so people can edit it and test it right away

**Comment by meteorplus** [comment]
Hello @brianzinn you can find a good app with SSR

https://github.com/cleverbeagle/pup

Sorry for the trouble

thanks

**Comment by brianzinn** [comment]
I tried different versions of babylonjs on that project *without* adding 'react-babylonjs', but only the 'babylonjs' and 'babylonjs-gui' NPM.  I ended up with these errors depending on the versions:

babylonjs-gui@3.2
W20180914-18:54:20.752(-7)? (STDERR) ReferenceError: Image is not defined
W20180914-18:54:20.753(-7)? (STDERR)     at ...\node_modules\babylonjs-gui\babylon.gui.min.js:3:9372

babylonjs-gui@3.3.0-beta.6
W20180915-10:43:18.125(-7)? (STDERR) ReferenceError: window is not defined
W20180915-10:43:18.132(-7)? (STDERR)     at Object.<anonymous> (E:\GitHub\tmp-ssr-delete-pup-master\node_modules\babylonjs-gui\babylon.gui.min.js:1:311)

It would appear that those errors are not because of SSR per se, but due to the GUI NPM unable to build universal.  Not sure how best to proceed here, as this issue is external to this specific library, but I'd like to try to help.  I would hope this works automatically when this issue (maybe in 3.3) is ready:
https://github.com/BabylonJS/Babylon.js/issues/3314

**Comment by brianzinn** [comment]
@meteorplus  can you share your workaround ie: are you using (typeof window !== 'undefined') or webpack with process.env - dynamically with a require(..)? thanks.

**Comment by meteorplus** [comment]
@brianzinn no no I'm pretty sure it's related to the SSR and Image there is an actual issue on bablyonjs
let me show you!
https://github.com/BabylonJS/Babylon.js/issues/3395
even adding this didn't work for me
```
let Canvas = require('canvas');
global.Image = Canvas.Image;
```
I ended up doing the dynamic import on the component then loading bablyonjs!

But the real issue is getting the viewer!!

**Comment by brianzinn** [comment]
Yes, it is absolutely related to SSR, but I meant during the build process as opposed to when generating the SSR pages, so there is nothing I can do in this library to address that.  Even the NPMs for excluding SSR in components will not help here - ie: 'react-no-ssr'.  Does not appear to be any way other than loading dynamically right now.

**Comment by brianzinn** [comment]
Actually, I should add that there are probably workarounds like using webpack with process.env to create a window object when needed:
window = {}

**Comment by meteorplus** [comment]
Nice but what about the viewer? 😃

**Comment by meteorplus** [comment]
thanks ;)
