### ISSUE TITLE
[discussion and proposal]: Animation

### ISSUE THREAD

**Issue by hookex** [brianzinn/react-babylonjs#53]
I would like to have a few full discussions with you and listen to your advice before we start coding.

Maybe we can do it in the following order.
- discuss
- form a proposal
- add it to the roadmap
- start to code

## Animation
Declarative programming paradigm is not easy for animations. I would like to simplify it.
There are there ways to animate.

#### 1. use `requestAnimationFrame()` and `setState()`

Each frame update involves a change in the state of the react tree.
This approach should have serious performance drawbacks.

#### 2. use `Babylonjs node` and `Babylonjs Animation`
This update restricts the impact to a node. So there are performance advantages.
In this way, there is a bit more redundant code.
Maybe there is a way to simplify it with `react features`

#### 3. with react-spring
I'm trying.
https://www.react-spring.io/docs/props/performance
https://github.com/react-spring/react-spring/blob/master/src/targets/three/index.ts

## [large-]data-driven animation
todo

**Comment by brianzinn** [comment]
This is a great idea!!  I've spent some time thinking about how to implement this as well - having a declarative option at least for loops would be a great start.  I want to share some existing stories that may add some insight:
1. The story you added uses rAF  and setState() - as you have mentioned in your proposal - it doesn't perform very well [demo](https://brianzinn.github.io/react-babylonjs/?path=/story/babylon-basic--transformnode).
2. We can use sceneOnBeforeRenderObservable().  There is a hook for it and it does perform well, but will be more difficult to integrate as an animation, since we can't leverage the existing built-in animation framework of BabylonJS (`useBeforeRender` does perform well [demo](https://brianzinn.github.io/react-babylonjs/?path=/story/physics-and-hooks--render-hooks) ).  Seems to have a glitch when it starts up and will be hard to do easing.
3. [gsapp tween demo](https://brianzinn.github.io/react-babylonjs/?path=/story/models--model-atom-gsap-tween).  Has hand-coding in example, but I think writing bindings for that misses a lot of built-in concepts like `easing functions` and `animation type` (ie: quaternion, vector, number, etc.).
4. React Spring - I think it is a worthwhile investigation and it is a well maintained project with lots of capabilities.
5. Bindings for BabylonJS animations may be the best of all worlds, because it will be able to directly integrate with the existing animations framework and map directly to the built-in animation concepts.

I'd be super happy to work with you on this as this will make it much more usable in real-world scenarios.  Let me know how I can help @hookex .

**Comment by hookex** [comment]
> 3\. [gsapp tween demo](https://brianzinn.github.io/react-babylonjs/?path=/story/models--model-atom-gsap-tween).
I didn't notice this example before. 
This can be replaced by `react-spring` and `babaylonjs Animation`.

> 4\. React Spring
It can simplify the animation code. react-spring native mode is performance-friendly.
But it needs extra work to connect `react-babylonjs` component.

> 5\. Bindings for BabylonJS animations
Maybe the combination of react and BabylonJS animation is a perfect way.

#### Share my final use case 

#### 1. transition of a large number of grouped meshes in a certain order.
This is about static react tree's change.

#### 2.[large-]data-driven real-time monitor
- receive data stream => parse data => data center(maybe redux) => animation timelines keys
- proper Animation Object(maybe BabylonJS Animation)
- connect component(BabylonJS mesh) with Animation
- tick with word timer


> Let me know how I can help @hookex .
Very grateful for your advice and code.
If you would like to look at my application's designed UI, I can send it to your email.

**Comment by brianzinn** [comment]
I sent you an email.  For the real-time monitor you may want to consider using redux-saga - it can connect to channels and sockets to stream data into redux.  We can try out different strategies and see what works best.  The main issue I see is that declaratively assigning animations makes it difficult to orchestrate animations across objects.  The babylonJS animations API lets you animate anything.

**Comment by hookex** [comment]
@brianzinn 

Connect react-babylon and  react-spring.
This is a simple demo(network slow)
http://118.24.23.94:8081/bviz/

#### Key files
https://github.com/hookex/bviz/blob/master/src/react-babylon-spring/index.ts
https://github.com/hookex/bviz/blob/1a9399272cdb142903cbde46897499e9a1711a1a/src/react-babylonjs/UpdateInstance.ts#L113
