### ISSUE TITLE
Release notes

### ISSUE THREAD

**Issue by AdrienLemaire** [brianzinn/react-babylonjs#96]
Can you write release notes when creating new git tags, to explain the new features, fixes, breaking changes & co?

This would be very much appreciated :bow:

**Comment by brianzinn** [comment]
Good Idea - I was losing track myself...  Too bad that github pages don't have some kind of mdx support to inline tags with commit messages.

I just added a way for me to manually add a comment when NPM publishing (using github actions) - there is no way to annotate the tag different from the version without using same name and forcing.  A comment is not as good as markdown release notes that shows breaking changes/new features - I usually try to write helpful commit messages, but I realize that doesn't make it clear if the upgrade is worthwhile.  Because I'm using `npm version` it's not linking the git tag to the previous commit, but actually there could be multiple branch commits.  At least by browsing the commit history you can easily see what changes are in each version.

Right now on the main readme there are two main categories for releases notes:
https://github.com/brianzinn/react-babylonjs#major-release-history
https://github.com/brianzinn/react-babylonjs#breaking-changes

I forgot to put in the upgrade to React 17 and including the reconciler as a non-peer dependency from a few releases back.  I was hoping to include them in v3, but it won't be ready for tomorrow when 4.2 is released, so decided to move a bunch of changes into the 2.x codebase and did a minor version bump to 2.3 yesterday to communicate it was a big change (the 2.2.15 release was a mistake).  I'm using github actions to do releases, so the new NPMs are manually triggered, but automatic.

You can see the version I just added was to fix textures (YAML needed the unicode, but it's not decoded... :) ):
![image](https://user-images.githubusercontent.com/542756/98907326-810ec580-2473-11eb-9c8a-c8c2710c8be4.png)

**Comment by AdrienLemaire** [comment]
@brianzinn thanks for the update and quick reply! 
Here's [the github doc](https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/managing-releases-in-a-repository) on 
As a side note, there seems to be several tools available to generate useful and nice-looking release notes, like [gren](https://github.com/github-tools/github-release-notes) :+1:

**Comment by brianzinn** [comment]
gren looks really good - thanks for the tip.  most NPM + github releases come directly from github issues and single commits (I tend to release to make changes available right away).  if you noticed the github actions do create a github release and tag, but it just has no meaningful information attached except a version # :)  generating a change.md would be a good next step!!

**Comment by brianzinn** [comment]
Feel free to re-open, but at least we have a start (linked to from main readme):
https://github.com/brianzinn/react-babylonjs/blob/master/CHANGELOG.md

It's not part of a build pipeline (github actions run manually!) yet, but that should just need to run the new script in package.json and commit the change for new NPM releases.
https://github.com/brianzinn/react-babylonjs/blob/master/package.json#L41
