### ISSUE TITLE
Particle System

### ISSUE THREAD

**Issue by dennemark** [brianzinn/react-babylonjs#98]
Hi,

I tried to add Particle System. Adding the following lines to the generate-code.ts allowed me to generate the JSX elements. However, I did not manage to get the storybook to work, since there were some issues with the react-babylon-loaders. I am not sure if the BaseParticleSystem needs to be added, since the other two are extension of it and I dont know if it needs Lifecycling. Would it be easy to add the Particle System?

Line 156
```
classesOfInterest.set("BaseParticleSystem", undefined);
classesOfInterest.set("ParticleSystem", undefined);
classesOfInterest.set("GPUParticleSystem", undefined);
```
Line 1622
```
  createSingleClass("BaseParticleSystem", generatedCodeSourceFile, generatedPropsSourceFile);
  createSingleClass("ParticleSystem", generatedCodeSourceFile, generatedPropsSourceFile);
  createSingleClass("GPUParticleSystem", generatedCodeSourceFile, generatedPropsSourceFile);
```

**Comment by brianzinn** [comment]
I need to do actually a bunch of cleanup.  One thing I will probably need to do is move the storybook to another project, because it's difficult to build.  I need to do a bunch on npm linking, build a custom 'react-three-gui' from a fork and remove module type from package.json.

I think it would be really cool to add particle system, but I just never got around to it.  I've used it quite a bit outside of React, so think it would be really useful.  I think we'd just need a way to pass in functions for the functionality.

I'm really excited that somebody else is trying out the code generator!  Let me do some cleanup there after work today to get it running for you tonight and some instructions.  Cheers.

**Comment by dennemark** [comment]
I could imagine that it is enough at first place to ref the particle system and write functions in i.e. onCreated or useEffect(()=>{...},[ref]). This would be enough for me probably. Currently I am handling node materials similarly - maybe I can share at some point.
The advantage with particleSystem as jsx element would be parenting within hierarchy and possibility to position declaratively.

I havent touched the v3 beta so far and probably wait for a bit of cleanup, since I dont want to break my project currently... :D  
Looking forward to trying it out though :)

**Comment by brianzinn** [comment]
I made the changes on master (it's a lot easier to work on than v3 branch!), so you should be able to get it going.  You need to use the `--no-dll` flag on storybook, because of React 17 (I think having Storybook is more maintenance than this whole project sometimes!).
`yarn storybook --no-dll`

There is also a create method that walks the class hierarchy (it will add all particle systems):
```
createClassesInheritedFrom(generatedCodeSourceFile, generatedPropsSourceFile, classesOfInterest.get("BaseParticleSystem")!, () => ({}));
```
I did see a few methods that weren't implemented, but if you go with direct access you should be good.  When I was thinking about it myself I had an idea to allow shapes to be added declaratively, but never made the time to see it through.  Let me know if you have any questions.
